#!/bin/sh
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config

cmd="$java -Djava.io.tmpdir=\"$tmp_dir\" -Dhttp.port=$port"
for file in `ls $control_dir/java-opts-* | sort`; do
    cmd="$cmd `cat $file`"
done

cmd="$cmd -cp \"$working/target/staged/*\" play.core.server.NettyServer $working $args"

exec bash -c "$cmd"
