#!/bin/sh
set -e
set -u

control_dir="$(dirname $PWD/$0)"
. $control_dir/config

cmd="$java -Djava.io.tmpdir=\"$tmp_dir\" -Dapp.port=$port -Dhttp.port=$port"
for file in `ls $control_dir/java-opts-* | sort`; do
    cmd="$cmd `cat $file`"
done

if [ -e "$working/target/start" ] then
    cmd="$cmd -cp \"$working/target/staged/*\" play.core.server.NettyServer $working $args"
else
    cmd="$cmd -cp \"$working/*/lib/*\" play.core.server.NettyServer $working/*/ $args"
fi

exec bash -c "$cmd"